//! NCCL collective backend for multi-GPU serving.
//!
//! ## Why multi-process
//!
//! Skein's compute runtime is Luminal's `CudaRuntime`, whose constructor
//! hardcodes `CudaContext::new(0)` (GPU 0) with no device-selection API on the
//! pinned rev. A single process therefore cannot place shards on distinct
//! GPUs. The portable solution — used by torchrun and every NCCL tensor/data-
//! parallel job — is **one process per rank**, each launched with
//! `CUDA_VISIBLE_DEVICES=<gpu>` (so the process's "device 0" is its assigned
//! GPU), the ranks joined into one communicator via `ncclCommInitRank` over a
//! shared unique id. The id is generated by the leader
//! ([`NcclCollective::new_id_bytes`]) and exchanged through
//! [`crate::distributed::rendezvous`]; the processes are spawned by
//! [`crate::distributed::launcher`].
//!
//! ## What this provides
//!
//! [`NcclCollective`] implements the same [`RankCollective`] trait as the CPU
//! [`crate::distributed::BarrierCollective`] reference, so the rank-parallel
//! execution logic is backend-agnostic: the CPU build validates it with
//! threads, the GPU build runs it over NCCL. The operations take host buffers
//! and stage them through device memory (H2D → NCCL → D2H). That matches the
//! current executor's host-`Vec<f32>` handoff path; keeping the buffers
//! resident on the device (zero-copy via Luminal's `set_device_ptr` /
//! `copy_output_to_device_ptr`) is a follow-up throughput optimization, not a
//! correctness change.
//!
//! ## Validation status
//!
//! This module is `#[cfg(feature = "cuda")]`-gated and cannot be compiled
//! without the CUDA toolkit, so it is validated on the GPU host, not in CI.
//! The collective logic and the cudarc call sequence follow cudarc 0.16.6's
//! documented `nccl` API (`Comm::from_rank`, `all_reduce`, `all_gather`,
//! `broadcast`, `Id`); the two calls most likely to need a signature touch-up
//! against the exact toolkit build are flagged inline (`NCCL-VALIDATE`).

use std::sync::Arc;

use cudarc::driver::CudaContext;
use cudarc::driver::CudaStream;
use cudarc::nccl::{Comm, Id, ReduceOp};

use crate::distributed::{CollectiveError, RankCollective};

/// One rank's NCCL communicator + its CUDA stream. Built once per process
/// after [`crate::distributed::launcher`] has set `CUDA_VISIBLE_DEVICES`, so
/// the visible device 0 is this rank's physical GPU.
pub struct NcclCollective {
    comm: Comm,
    stream: Arc<CudaStream>,
    rank: usize,
    world_size: usize,
    /// Reused device recv buffer for the in-place bf16 device all-reduce, so the
    /// steady-state path does no per-call `alloc_zeros`. Interior-mutable because
    /// the collective is borrowed `&self` per step (single rank thread).
    recv_cache: std::cell::RefCell<Option<cudarc::driver::CudaSlice<half::bf16>>>,
}

impl NcclCollective {
    /// Generate a fresh NCCL unique id (the leader rank calls this) and return
    /// its raw bytes for publishing over the rendezvous file.
    pub fn new_id_bytes() -> Result<Vec<u8>, CollectiveError> {
        let id = Id::new().map_err(|e| CollectiveError::Nccl(format!("ncclGetUniqueId: {e:?}")))?;
        Ok(id.internal().iter().map(|&b| b as u8).collect())
    }

    /// Join the NCCL group as `rank` of `world_size`, using the leader's id
    /// bytes (from the rendezvous). The process must already have
    /// `CUDA_VISIBLE_DEVICES` set so device 0 is this rank's GPU.
    pub fn init(rank: usize, world_size: usize, id_bytes: &[u8]) -> Result<Self, CollectiveError> {
        if world_size == 0 || rank >= world_size {
            return Err(CollectiveError::BadLayout { rank, world_size });
        }
        let ctx = CudaContext::new(0)
            .map_err(|e| CollectiveError::Nccl(format!("CudaContext::new(0): {e}")))?;
        let stream = ctx.default_stream();
        let id = id_from_bytes(id_bytes)?;
        let comm = Comm::from_rank(stream.clone(), rank, world_size, id)
            .map_err(|e| CollectiveError::Nccl(format!("ncclCommInitRank: {e:?}")))?;
        Ok(Self {
            comm,
            stream,
            rank,
            world_size,
            recv_cache: std::cell::RefCell::new(None),
        })
    }
}

impl RankCollective for NcclCollective {
    fn rank(&self) -> usize {
        self.rank
    }

    fn world_size(&self) -> usize {
        self.world_size
    }

    fn all_reduce_sum(&self, buf: &mut [f32]) -> Result<(), CollectiveError> {
        // NCCL-VALIDATE: `memcpy_stod` / `alloc_zeros` / `memcpy_dtov` are the
        // cudarc 0.16 stream helpers; confirm exact names against the toolkit.
        let send = self.stream.memcpy_stod(buf).map_err(cuda_err)?;
        let mut recv = self
            .stream
            .alloc_zeros::<f32>(buf.len())
            .map_err(cuda_err)?;
        self.comm
            .all_reduce(&send, &mut recv, &ReduceOp::Sum)
            .map_err(|e| CollectiveError::Nccl(format!("ncclAllReduce: {e:?}")))?;
        self.stream.synchronize().map_err(cuda_err)?;
        let host = self.stream.memcpy_dtov(&recv).map_err(cuda_err)?;
        buf.copy_from_slice(&host);
        Ok(())
    }

    fn all_gather(&self, buf: &[f32]) -> Result<Vec<f32>, CollectiveError> {
        let send = self.stream.memcpy_stod(buf).map_err(cuda_err)?;
        let mut recv = self
            .stream
            .alloc_zeros::<f32>(buf.len() * self.world_size)
            .map_err(cuda_err)?;
        self.comm
            .all_gather(&send, &mut recv)
            .map_err(|e| CollectiveError::Nccl(format!("ncclAllGather: {e:?}")))?;
        self.stream.synchronize().map_err(cuda_err)?;
        self.stream.memcpy_dtov(&recv).map_err(cuda_err)
    }

    fn broadcast(&self, buf: &mut [f32], root: usize) -> Result<(), CollectiveError> {
        let send = self.stream.memcpy_stod(buf).map_err(cuda_err)?;
        let mut recv = self
            .stream
            .alloc_zeros::<f32>(buf.len())
            .map_err(cuda_err)?;
        self.comm
            .broadcast(Some(&send), &mut recv, root as i32)
            .map_err(|e| CollectiveError::Nccl(format!("ncclBroadcast: {e:?}")))?;
        self.stream.synchronize().map_err(cuda_err)?;
        let host = self.stream.memcpy_dtov(&recv).map_err(cuda_err)?;
        buf.copy_from_slice(&host);
        Ok(())
    }

    unsafe fn all_reduce_sum_device_bf16(
        &self,
        ptr: u64,
        elems: usize,
    ) -> Result<(), CollectiveError> {
        use std::mem::ManuallyDrop;
        if ptr == 0 || elems == 0 {
            return Ok(());
        }
        // View the producer segment's output buffer as bf16 WITHOUT taking
        // ownership (ManuallyDrop ⇒ no cuMemFree on drop; the Luminal arena owns
        // it). NCCL all-reduces device→device; the result is copied back into the
        // same buffer so the consumer that binds this pointer reads the reduced
        // activation. No host staging anywhere on this path.
        let mut send =
            ManuallyDrop::new(unsafe { self.stream.upgrade_device_ptr::<half::bf16>(ptr, elems) });
        // Reuse a cached recv buffer (cudarc all_reduce uses recv.len() as the
        // element count, so it must match `elems` exactly). All RingAllReduce
        // activations in decode share the same hidden width, so this reallocs
        // ~once and then reuses every step.
        let mut cache = self.recv_cache.borrow_mut();
        if cache.as_ref().map(|b| b.len()) != Some(elems) {
            *cache = Some(
                self.stream
                    .alloc_zeros::<half::bf16>(elems)
                    .map_err(cuda_err)?,
            );
        }
        let recv = cache.as_mut().unwrap();
        self.comm
            .all_reduce(&*send, recv, &ReduceOp::Sum)
            .map_err(|e| CollectiveError::Nccl(format!("ncclAllReduce(bf16): {e:?}")))?;
        // In-place result: copy the reduced buffer back over the producer buffer
        // (device→device). All of all-reduce, this copy, and the consumer segment
        // run on the legacy default stream, so they are ordered without a
        // per-call host synchronize; the forward flushes at the logits all-gather.
        self.stream
            .memcpy_dtod(recv, &mut *send)
            .map_err(cuda_err)?;
        Ok(())
    }
}

fn cuda_err(e: cudarc::driver::DriverError) -> CollectiveError {
    CollectiveError::Nccl(format!("cuda: {e}"))
}

/// Point-to-point KV-block transfer over NCCL — the topology's `NcclByLayer`
/// prefill/decode-disaggregation protocol. A prefill rank sends the KV blocks
/// it computed for a request to the decode rank that will continue it, so
/// decode skips recomputing the prompt. Built on the same `cudarc::nccl`
/// primitives as [`NcclCollective`]; blocks are staged through host memory
/// (H2D → ncclSend / ncclRecv → D2H), matching the collective buffer model.
/// (Keeping the KV resident on-device — zero-copy via Luminal's device-pointer
/// API — is the same follow-up optimization noted for the collectives.)
pub struct NcclKvTransport {
    comm: Comm,
    stream: Arc<CudaStream>,
    rank: usize,
    world_size: usize,
}

impl NcclKvTransport {
    /// Join the prefill+decode process group's communicator. `id_bytes` is the
    /// shared NCCL id from the rendezvous; `rank`/`world_size` cover both pools.
    pub fn init(rank: usize, world_size: usize, id_bytes: &[u8]) -> Result<Self, CollectiveError> {
        if world_size == 0 || rank >= world_size {
            return Err(CollectiveError::BadLayout { rank, world_size });
        }
        let ctx = CudaContext::new(0)
            .map_err(|e| CollectiveError::Nccl(format!("CudaContext::new(0): {e}")))?;
        let stream = ctx.default_stream();
        let id = id_from_bytes(id_bytes)?;
        let comm = Comm::from_rank(stream.clone(), rank, world_size, id)
            .map_err(|e| CollectiveError::Nccl(format!("ncclCommInitRank: {e:?}")))?;
        Ok(Self {
            comm,
            stream,
            rank,
            world_size,
        })
    }

    pub fn rank(&self) -> usize {
        self.rank
    }

    pub fn world_size(&self) -> usize {
        self.world_size
    }

    /// Send the request's KV `blocks` (one host buffer per layer/block) to the
    /// `peer` decode rank. Unidirectional (sender only sends), so no group is
    /// needed; the receiver must post a matching [`recv_blocks`].
    pub fn send_blocks(&self, blocks: &[Vec<f32>], peer: usize) -> Result<(), CollectiveError> {
        for block in blocks {
            // NCCL-VALIDATE: cudarc 0.16 stream memcpy helper names.
            let dev = self.stream.memcpy_stod(block).map_err(cuda_err)?;
            self.comm
                .send(&dev, peer as i32)
                .map_err(|e| CollectiveError::Nccl(format!("ncclSend: {e:?}")))?;
        }
        self.stream.synchronize().map_err(cuda_err)?;
        Ok(())
    }

    /// Receive `count` KV blocks of `block_len` elements each from the `peer`
    /// prefill rank, in send order.
    pub fn recv_blocks(
        &self,
        peer: usize,
        count: usize,
        block_len: usize,
    ) -> Result<Vec<Vec<f32>>, CollectiveError> {
        let mut out = Vec::with_capacity(count);
        for _ in 0..count {
            let mut dev = self
                .stream
                .alloc_zeros::<f32>(block_len)
                .map_err(cuda_err)?;
            self.comm
                .recv(&mut dev, peer as i32)
                .map_err(|e| CollectiveError::Nccl(format!("ncclRecv: {e:?}")))?;
            out.push(self.stream.memcpy_dtov(&dev).map_err(cuda_err)?);
        }
        self.stream.synchronize().map_err(cuda_err)?;
        Ok(out)
    }
}

/// Reconstruct an NCCL [`Id`] from the leader's raw bytes.
///
/// NCCL-VALIDATE: the byte layout is `ncclUniqueId` (128 `c_char`). cudarc
/// exposes the id's internal array via `Id::internal`; this rebuilds it through
/// `Id::uninit` + an internal copy. If the exact 0.16.6 API differs (e.g. a
/// `from`/`from_bytes` constructor), adjust here — the wire format is fixed.
fn id_from_bytes(bytes: &[u8]) -> Result<Id, CollectiveError> {
    const N: usize = 128;
    if bytes.len() != N {
        return Err(CollectiveError::Nccl(format!(
            "nccl id must be {N} bytes, got {}",
            bytes.len()
        )));
    }
    // cudarc reconstructs an `Id` from its raw 128-`c_char` wire form via
    // `Id::uninit(array)`. Mirror `new_id_bytes`'s `i8 -> u8` serialization.
    let mut arr = [0 as std::ffi::c_char; 128];
    for (a, &b) in arr.iter_mut().zip(bytes.iter()) {
        *a = b as std::ffi::c_char;
    }
    Ok(Id::uninit(arr))
}
