//! File-based rendezvous for the NCCL unique id.
//!
//! `ncclCommInitRank` requires every rank to share one unique id generated by
//! a single rank. On a single node the simplest reliable channel is a shared
//! file on a path all ranks agree on (set by the [`super::launcher`]): the
//! leader (rank 0) generates the id and [`publish`]es it atomically; every
//! other rank [`fetch`]es it, polling until it appears. The id bytes are
//! opaque here — the NCCL backend produces them with `Id::new()` and consumes
//! them with `Id::uninit(...)`; this module only moves the bytes.

use std::io::{Read, Write};
use std::path::Path;
use std::time::{Duration, Instant};

use super::CollectiveError;

/// Write `id_bytes` to `path` atomically: write a temp sibling then rename, so
/// a peer polling `path` never observes a partially written id.
pub fn publish(path: &Path, id_bytes: &[u8]) -> Result<(), CollectiveError> {
    let rendezvous_err = |source| CollectiveError::Rendezvous {
        path: path.display().to_string(),
        source,
    };
    if let Some(parent) = path.parent() {
        if !parent.as_os_str().is_empty() {
            std::fs::create_dir_all(parent).map_err(rendezvous_err)?;
        }
    }
    let tmp = path.with_extension("rendezvous.tmp");
    {
        let mut f = std::fs::File::create(&tmp).map_err(|source| CollectiveError::Rendezvous {
            path: tmp.display().to_string(),
            source,
        })?;
        f.write_all(id_bytes).and_then(|_| f.sync_all()).map_err(|source| {
            CollectiveError::Rendezvous {
                path: tmp.display().to_string(),
                source,
            }
        })?;
    }
    std::fs::rename(&tmp, path).map_err(rendezvous_err)
}

/// Poll `path` until it exists, then read and return its bytes. Errors with
/// [`CollectiveError::RendezvousTimeout`] if it does not appear within
/// `timeout`.
pub fn fetch(path: &Path, timeout: Duration) -> Result<Vec<u8>, CollectiveError> {
    let start = Instant::now();
    let poll = Duration::from_millis(20);
    loop {
        match std::fs::File::open(path) {
            Ok(mut f) => {
                let mut buf = Vec::new();
                f.read_to_end(&mut buf).map_err(|source| CollectiveError::Rendezvous {
                    path: path.display().to_string(),
                    source,
                })?;
                if !buf.is_empty() {
                    return Ok(buf);
                }
                // File exists but is empty (rare race with a non-atomic writer);
                // keep polling.
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(source) => {
                return Err(CollectiveError::Rendezvous {
                    path: path.display().to_string(),
                    source,
                });
            }
        }
        if start.elapsed() >= timeout {
            return Err(CollectiveError::RendezvousTimeout {
                ms: timeout.as_millis() as u64,
                path: path.display().to_string(),
            });
        }
        std::thread::sleep(poll);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tmp_path(name: &str) -> std::path::PathBuf {
        let mut p = std::env::temp_dir();
        p.push(format!(
            "skein_rdv_{}_{}",
            name,
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        p
    }

    #[test]
    fn publish_then_fetch_round_trips() {
        let path = tmp_path("roundtrip");
        let id = (0u8..128).collect::<Vec<_>>();
        publish(&path, &id).expect("publish");
        let got = fetch(&path, Duration::from_secs(1)).expect("fetch");
        assert_eq!(got, id);
        let _ = std::fs::remove_file(&path);
    }

    #[test]
    fn fetch_times_out_when_absent() {
        let path = tmp_path("absent");
        let err = fetch(&path, Duration::from_millis(60)).unwrap_err();
        assert!(matches!(err, CollectiveError::RendezvousTimeout { .. }));
    }

    #[test]
    fn fetch_waits_for_a_late_publish() {
        let path = tmp_path("late");
        let writer_path = path.clone();
        let h = std::thread::spawn(move || {
            std::thread::sleep(Duration::from_millis(40));
            publish(&writer_path, b"hello-nccl").unwrap();
        });
        let got = fetch(&path, Duration::from_secs(2)).expect("fetch waits");
        assert_eq!(got, b"hello-nccl");
        h.join().unwrap();
        let _ = std::fs::remove_file(&path);
    }
}
